### ISSUE TITLE
Tedious map constructors

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/flurry#51]
Since `HashMap`'s various constructors are now generic over `S where S: Default`, you now often have to explicitly write something like:
```rust
let map: HashMap<_, _> = HashMap::new();
```
This is strictly more generic (it'll work with any `S`), but it's also kind of annoying. One option is to basically undo https://github.com/jonhoo/flurry/commit/17d138f62573b33397cfaaa89fc5cfcf30186503 and have those methods _just_ be implemented for the `DefaultHashBuilder` instead. That would make the above (and much other code) not have to repeat the type. Thoughts?

**Comment by cuviper** [comment]
In the standard `HashMap`, `new` and `with_capacity` are only defined with the default `S`.
https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.new

Otherwise, you have to use the constructors with an actual instance: `with_hasher` and `with_capacity_and_hasher`. The only time `S: Default` is required and used is for `Default` and `FromIterator`.

**Comment by jonhoo** [comment]
Fixed by https://github.com/jonhoo/flurry/pull/52.
