### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/flurry#8]
We should port the single-core benchmarks [from `hashbrown`](https://github.com/rust-lang/hashbrown/blob/master/benches/bench.rs), and the concurrent ones [from `dashmap`](https://github.com/xacrimon/dashmap/tree/master/benches) to measure the performance of flurry!

**Comment by domenicquirl** [comment]
How do you feel about the dependencies for this? `dashmap` uses `criterion` which, [according to their docs](https://docs.rs/criterion/0.3.1/criterion/macro.criterion_main.html) only works if one disables the default benchmarking harness generated by `test`. On the contrary, `hashbrown` uses `test` and its `Bencher`. (Also `dashmap` uses `rayon`, but since we have #14 this might be added anyway).

Since `test::bench` is, I believe, still feature-gated and nightly-only, it might be easier to rewrite the `hashbrown` macros to use criterion, but either way we should probably settle on one solution for all benchmarks.

I'll start with the `dashmap` benches once this is clear.

**Comment by jonhoo** [comment]
I think `criterion` is the way to go!

**Comment by domenicquirl** [comment]
Alright! I'll open a PR when I got some code!

**Comment by domenicquirl** [comment]
This can now be closed as #43 is merged 😊
