### ISSUE TITLE
Finish the safety argument for `BinEntry::Moved`

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/flurry#9]
The safety argument for why dereferencing the pointer in `BinEntry::Moved` has not been completed. It currently stands with a `FIXME` in case three here
https://github.com/jonhoo/flurry/blob/d3dae0465b37b7f12c4f0d58a16f36fb1d8c1596/src/lib.rs#L474-L492
and case two here
https://github.com/jonhoo/flurry/blob/6d56c58026f6edd0d9828ce48b3cbb6aecd38973/src/lib.rs#L1060-L1072

**Comment by domenicquirl** [comment]
I'm thinking as follows: If we perform an operation that sees a `Moved(t)`, we must have gotten there by _loading_ `self.table` with a guard `g`. This guard `g` will pin an epoch _before_ the resize is finished with respect to the loaded table, otherwise we would have loaded the next table. This argument also exists here:
https://github.com/jonhoo/flurry/blob/051ca79fe2458af0e0e75ab93f8cd113078cd2bd/src/map.rs#L719-L749

- During the resize, `t` points to `next_table` and is thus valid.
- After the resize, `t == self.table`, thus `t` is valid.
- This holds until a subsequent resize ends, at which point `self.table != t` and `t` is `defer_destroy`ed (see the code above). At this point, `t` is not referenced by the map anymore. However, the `defer_destroy` happens while `g` is still pinning the epoch. Thus, `t` remains valid for at least the lifetime of `g`.
- After releasing `g`, performing operations on the map with a new guard `g'` cannot access the table anymore (also see above).

Since this traces the entire lifetime of both the guard and the table and in particular, the above code is the only place that `defer_destroy`s tables, I think the argument is sound. What do you think?

**Comment by jonhoo** [comment]
Yes, that seems correct to me as well! Could you submit a PR with that argument included? I think maybe we want to make that argument as a comment on the `Moved` variant of `BinEntry` (rather than in everywhere that uses it), and then reference that argument from the two or three places that rely on it.

**Comment by domenicquirl** [comment]
Nice! I just created #35 for this. I was also already thinking about reducing redundancy with these comments, but wasn't sure where to put them yet. The definition of `Moved` seems like a good place!

There is also some other PR i saw which had copied the argument, I'll go find it and tell them about the PR so that we don't introduce more copies of the FIXME again 😉
